steps:
  - id: "Install dependencies"
    name: node
    entrypoint: npm
    dir: "./functions"
    args: ["install"]

  - id: "Running tests"
    name: node
    entrypoint: npm
    dir: "./functions"
    args: ["test", "--", "--passWithNoTests"]

  - id: Deploying to Firebase
    name: "gcr.io/$PROJECT_ID/firebase"
    args: ["deploy", "--project=$PROJECT_ID", "--only=functions"]
