steps:
  - id: Install dependencies
    name: node
    entrypoint: npm
    dir: "./web"
    args: ["install"]

  - id: Running tests
    name: node
    entrypoint: npm
    dir: "./web"
    args: ["test", "--passWithNoTests"]
    env:
      - "CI=true"

  - id: Build app
    name: node
    entrypoint: npm
    dir: "./web"
    args: ["run", "build"]

  - id: Deploying to Firebase
    name: "gcr.io/$PROJECT_ID/firebase"
    args: ["deploy", "--project=$PROJECT_ID", "--only=hosting"]
